server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**


        - id: api-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/**
          filters:
            - name: ValidateTokenFilter
              args:
                excludePaths: /api/public